### ISSUE TITLE
Access modifiers of some methods should be reconsidered.

### ISSUE THREAD

**Issue by nisiguti** [personium/personium-client-java#11]
- necessity of public
  - for example, 'public void setAccessType(String accessType)' of Accessor class
- appropriate use of protected, private, package
  - for example, 'protected void certification()' and 'String getAccessType()' of Accessor class
    In a derived class, certification() is able to be overridden, but getAccessType() is not usable.

**Comment by SawamiWataru** [comment]
Solved in v1.4.5.
