### ISSUE TITLE
Allow depth to be 0 for some function

### ISSUE THREAD

**Issue by dixonsiu** [personium/personium-client-java#26]
When trying to get ACL information, we don't need the child's ACL.  
['public PersoniumResponse propfind(String url) throws DaoException'](https://github.com/personium/personium-client-java/blob/master/src/main/java/io/personium/client/http/RestAdapter.java#L627)   should support both 0 and 1 depth.

**Comment by SawamiWataru** [comment]
Released v1.4.9
