### ISSUE TITLE
Transcell token is not issued.

### ISSUE THREAD

**Issue by nisiguti** [personium/personium-client-java#8]
cell_target is an incorrect parameter. p_target is correct.

https://github.com/personium/personium-client-java/blob/master/src/main/java/io/personium/client/Accessor.java#L780
https://github.com/personium/personium-client-java/blob/master/src/main/java/io/personium/client/Accessor.java#L798

**Comment by nisiguti** [comment]
Please add me as a collaborator on this repository.

**Comment by shimono** [comment]
Fix PR is merged, so this issue will be fixed in the next release.

**Comment by SawamiWataru** [comment]
Solved in v1.4.5.
