### ISSUE TITLE
Branch '1.4.4' is not merged to master branch. 

### ISSUE THREAD

**Issue by nisiguti** [personium/personium-client-java#9]
Current release version is 1.4.4 and develop version is 1.4.5-dev.
But branch '1.4.4' still exists not to be merged and a bug fixed on branch '1.4.4' is not applied to branch '1.4.5-dev'.

**Comment by hideakikondo** [comment]
`1.4.4` branch's bug fixes have been merged to `1.4.5-dev` and `master`.
